package models.GameWorld.Map;

public enum TerrainType {
    HUT, GREENHOUSE, QUARRY, LAKE,
    BLACKSMITH, JOJA_MART, GENERAL_STORE, CARPENTER_SHOP, FISH_SHOP, MARNIE_RANCH, STARDROP_SALOON,
    DIRT, PLOWED_DIRT,
    GRASS, SAND, FOREST, ROCKS, SNOW
}
